In [12]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [13]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [14]:
np.array(list_)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [15]:
l = [1,2,3,45]
a = np.array(l)

In [16]:
a

array([ 1,  2,  3, 45])

In [17]:
type(a)

numpy.ndarray

In [18]:
type(list_)

list

In [19]:
# ANS 1:
# variables list_ is just a list data structure that stores elements
# arrat list_ is numpy array which stores elements in one dimension array

In [34]:
# ANS 2:
print(a)
for i in a:
    print(i.dtype)

[ 1  2  3 45]
int64
int64
int64
int64


In [35]:
print(array_list)
for i in array_list:
    print(i.dtype)

['1' '2' '3' '4' '5']
<U1
<U1
<U1
<U1
<U1


In [39]:
# ANS 3:

In [48]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
arra_list = np.array(object = list_ , dtype=int)
# yes the datatype of each element changes integer

In [49]:
for i in arra_list:
    print(i.dtype)

int64
int64
int64
int64
int64


In [50]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [56]:
# ANS 4
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
num_array.shape

(2, 3)

In [58]:
num_array.size

6

In [67]:
# ANS 5 :
np.array([[0,0,0],[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [69]:
# ANS 6:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])